### PR TITLE
Add annotations processed for itk-vtk-viewer

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@thewtex If that format looks ok to you, can you merge this?  I'd like to start fetching it right away. 
 Otherwise, let me know and I can change it quickly.

**Comment by scottwittenburg** [comment]
I can turn it into a notebook later too, maybe that's what you prefer...

**Comment by scottwittenburg** [comment]
@thewtex I looked it up, and a serialized JSON object can start with either `{` or `[` (for example, see the accepted answer [here](https://stackoverflow.com/questions/5034444/can-json-start-with)).

However, I'm happy to make this an object instead of an array if you want.  In that case, what key name would you want for the list within the top level object?  Something like:

```json
{
  "annotation_list": [
    [0, "blah (blah)"],
    ...
  ]
}
```

**Comment by thewtex** [comment]
@scottwittenburg thanks for the update and investigation :+1:

**Pull request merged**
